### ISSUE TITLE
gdev shell returning error response from daemon

### ISSUE THREAD

**Issue by tombrunberg** [devgeniem/gdev#3]
After updating ( gdev update ), gdev shell causes following error
Error response from daemon: client is newer than server (client API version: 1.23, server API version: 1.22)

**Comment by onnimonni** [comment]
It seems that the `dlite` machine needs to be updated as well. Can you try running: `$ dlite rebuild`?

**Comment by onnimonni** [comment]
Seems that newer docker client version isn't compatible with version which dlite is using.

This fixed it for me:
`$ brew switch docker 1.10.3`

**Comment by onnimonni** [comment]
This was also related to dlite and this doesn't happen anymore with docker for mac.
