### ISSUE TITLE
Running the install script returns an error

### ISSUE THREAD

**Issue by drawpause** [devgeniem/gdev#5]
`fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"backup": false, "block": "", "content": null, "create": false, "delimiter": null, "dest": "/etc/exports", "directory_mode": null, "follow": false, "force": null, "group": null, "insertafter": null, "insertbefore": null, "marker": ": dlite", "mode": null, "owner": null, "regexp": null, "remote_src": null, "selevel": null, "serole": null, "setype": null, "seuser": null, "src": null, "state": "absent", "validate": null}, "module_name": "blockinfile"}, "msg": "Destination /etc/exports does not exist !", "rc": 257}`

**Comment by onnimonni** [comment]
This is because we were using `dlite` for running docker before and it included few hacks which we needed to apply to the system. This isn't needed anymore so I should add check to only do this when the file exists.
